# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-08 01:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_billingprofile_customer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingprofile',
            old_name='updated',
            new_name='update',
        ),
    ]
